# Generated by Django 5.0.2 on 2024-02-10 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("myapp", "0002_rename_user_customuser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="User",
        ),
    ]
