# Generated by Django 5.0.2 on 2024-02-11 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="pub_time",
        ),
    ]
