# Generated by Django 5.0.2 on 2024-02-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_message_pub_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="pub_time",
            field=models.DateTimeField(auto_now=True, verbose_name="作成日時"),
        ),
    ]
